name: "Terraform Destroy"

on:
  workflow_dispatch:

jobs:
  destroy:
    name: "Exoscale Infrastructure Teardown"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init
        working-directory: ./Abgabe_2_270526

      - name: Terraform Destroy (Infrastruktur loeschen)
        run: |
          terraform destroy -auto-approve \
            -var="exoscale_key=${{ secrets.EXOSCALE_API_KEY }}" \
            -var="exoscale_secret=${{ secrets.EXOSCALE_API_SECRET }}" \
            -var="zone=at-vie-1"
        working-directory: ./Abgabe_2_270526
